name: Update Parent Submodule

on:
  push:
    branches:
      - main

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v4
        with:
          repository: mikhalexandr/itmo-cse-labs
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Update submodule reference
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git submodule update --remote programming

          if [[ -n $(git status -s) ]]; then
            git add programming
            git commit -m "Auto-update submodule: itmo-cse-programming"
            git push
            echo "Parent repository updated!"
          else
            echo "No changes in submodule."
          fi
